# Generated by Django 5.1.4 on 2025-03-31 11:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='messagethread',
            name='slug',
            field=models.CharField(blank=True, max_length=255, unique=True, verbose_name='الرابط المختصر'),
        ),
        migrations.AlterField(
            model_name='auction',
            name='slug',
            field=models.CharField(max_length=255, unique=True, verbose_name='الرابط المختصر'),
        ),
        migrations.AlterField(
            model_name='property',
            name='slug',
            field=models.CharField(blank=True, max_length=255, unique=True, verbose_name='الرابط المختصر'),
        ),
        migrations.AddIndex(
            model_name='messagethread',
            index=models.Index(fields=['slug'], name='message_thr_slug_0fa027_idx'),
        ),
    ]
