# Generated by Django 5.1.4 on 2025-04-04 18:28

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_messagethread_slug_alter_auction_slug_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='messagethread',
            new_name='idx_thread_type',
            old_name='message_thr_thread__6f5b46_idx',
        ),
        migrations.RenameIndex(
            model_name='messagethread',
            new_name='idx_status',
            old_name='message_thr_status_071b64_idx',
        ),
        migrations.RenameIndex(
            model_name='messagethread',
            new_name='idx_creator',
            old_name='message_thr_creator_9569df_idx',
        ),
        migrations.RenameIndex(
            model_name='messagethread',
            new_name='idx_related_property',
            old_name='message_thr_related_9b664f_idx',
        ),
        migrations.RenameIndex(
            model_name='messagethread',
            new_name='idx_related_auction',
            old_name='message_thr_related_d06e8b_idx',
        ),
        migrations.RenameIndex(
            model_name='messagethread',
            new_name='idx_related_contract',
            old_name='message_thr_related_ced6a9_idx',
        ),
        migrations.RenameIndex(
            model_name='messagethread',
            new_name='idx_is_private',
            old_name='message_thr_is_priv_a9c0df_idx',
        ),
        migrations.RenameIndex(
            model_name='messagethread',
            new_name='idx_is_system_thread',
            old_name='message_thr_is_syst_3f56d1_idx',
        ),
        migrations.RenameIndex(
            model_name='messagethread',
            new_name='idx_last_message_at',
            old_name='message_thr_last_me_475f12_idx',
        ),
        migrations.RenameIndex(
            model_name='messagethread',
            new_name='idx_timestamps',
            old_name='message_thr_created_1d2a3d_idx',
        ),
        migrations.RenameIndex(
            model_name='messagethread',
            new_name='idx_slug',
            old_name='message_thr_slug_0fa027_idx',
        ),
        migrations.AlterField(
            model_name='auction',
            name='auctioneer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_auctions', to=settings.AUTH_USER_MODEL, verbose_name='منظم المزاد'),
        ),
        migrations.AlterField(
            model_name='auction',
            name='buyer_premium_percent',
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='نسبة عمولة المشتري'),
        ),
        migrations.AlterField(
            model_name='auction',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_auctions', to=settings.AUTH_USER_MODEL, verbose_name='تم الإنشاء بواسطة'),
        ),
        migrations.AlterField(
            model_name='auction',
            name='deposit_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='مبلغ التأمين'),
        ),
        migrations.AlterField(
            model_name='auction',
            name='min_bid_increment',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='الحد الأدنى للزيادة'),
        ),
        migrations.AlterField(
            model_name='auction',
            name='reserve_price',
            field=models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='السعر الاحتياطي'),
        ),
        migrations.AlterField(
            model_name='auction',
            name='seller_commission_percent',
            field=models.DecimalField(decimal_places=2, default=2.5, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='نسبة عمولة البائع'),
        ),
        migrations.AlterField(
            model_name='auction',
            name='starting_price',
            field=models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='سعر البدء'),
        ),
        migrations.AlterField(
            model_name='bid',
            name='bid_amount',
            field=models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='قيمة العطاء'),
        ),
        migrations.AlterField(
            model_name='bid',
            name='bidder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bids', to=settings.AUTH_USER_MODEL, verbose_name='المزايد'),
        ),
        migrations.AlterField(
            model_name='bid',
            name='max_bid_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='الحد الأقصى للمزايدة التلقائية'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='commission_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='قيمة العمولة'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='contract_amount',
            field=models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='قيمة العقد'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='deposit_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='قيمة العربون'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='قيمة الضريبة'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='المبلغ الإجمالي'),
        ),
        migrations.AlterField(
            model_name='messagethread',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='When the thread was created.', verbose_name='تاريخ الإنشاء'),
        ),
        migrations.AlterField(
            model_name='messagethread',
            name='creator',
            field=models.ForeignKey(help_text='User who created the thread.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_threads', to=settings.AUTH_USER_MODEL, verbose_name='منشئ المحادثة'),
        ),
        migrations.AlterField(
            model_name='messagethread',
            name='is_private',
            field=models.BooleanField(default=False, help_text='Whether the thread is private.', verbose_name='محادثة خاصة'),
        ),
        migrations.AlterField(
            model_name='messagethread',
            name='is_system_thread',
            field=models.BooleanField(default=False, help_text='Whether the thread is system-generated.', verbose_name='محادثة نظام'),
        ),
        migrations.AlterField(
            model_name='messagethread',
            name='last_message_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp of the most recent message.', null=True, verbose_name='تاريخ آخر رسالة'),
        ),
        migrations.AlterField(
            model_name='messagethread',
            name='related_auction',
            field=models.ForeignKey(blank=True, help_text='Auction associated with this thread, if any.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='message_threads', to='base.auction', verbose_name='المزاد المرتبط'),
        ),
        migrations.AlterField(
            model_name='messagethread',
            name='related_contract',
            field=models.ForeignKey(blank=True, help_text='Contract associated with this thread, if any.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='message_threads', to='base.contract', verbose_name='العقد المرتبط'),
        ),
        migrations.AlterField(
            model_name='messagethread',
            name='related_property',
            field=models.ForeignKey(blank=True, help_text='Property associated with this thread, if any.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='message_threads', to='base.property', verbose_name='العقار المرتبط'),
        ),
        migrations.AlterField(
            model_name='messagethread',
            name='slug',
            field=models.CharField(blank=True, help_text='URL-friendly identifier for the thread.', max_length=255, unique=True, verbose_name='الرابط المختصر'),
        ),
        migrations.AlterField(
            model_name='messagethread',
            name='status',
            field=models.CharField(choices=[('active', 'نشط'), ('closed', 'مغلق'), ('archived', 'مؤرشف'), ('deleted', 'محذوف')], default='active', help_text='Current status of the thread.', max_length=20, verbose_name='حالة المحادثة'),
        ),
        migrations.AlterField(
            model_name='messagethread',
            name='subject',
            field=models.CharField(help_text='Subject of the conversation thread.', max_length=255, verbose_name='الموضوع'),
        ),
        migrations.AlterField(
            model_name='messagethread',
            name='thread_type',
            field=models.CharField(choices=[('inquiry', 'استفسار'), ('support', 'دعم'), ('negotiation', 'تفاوض'), ('general', 'عام'), ('notification', 'إشعار'), ('system', 'نظام')], default='general', help_text='Type of conversation (e.g., inquiry, support).', max_length=20, verbose_name='نوع المحادثة'),
        ),
        migrations.AlterField(
            model_name='messagethread',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='When the thread was last updated.', verbose_name='تاريخ التحديث'),
        ),
        migrations.AlterField(
            model_name='messagethread',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the thread.', unique=True, verbose_name='المعرف العالمي'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='المبلغ'),
        ),
        migrations.AlterField(
            model_name='property',
            name='area',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='مساحة العقار'),
        ),
        migrations.AlterField(
            model_name='property',
            name='asking_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='السعر المطلوب'),
        ),
        migrations.AlterField(
            model_name='property',
            name='built_up_area',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='المساحة المبنية'),
        ),
        migrations.AlterField(
            model_name='property',
            name='estimated_value',
            field=models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='القيمة التقديرية'),
        ),
        migrations.AlterField(
            model_name='property',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_properties', to=settings.AUTH_USER_MODEL, verbose_name='المالك'),
        ),
        migrations.AlterField(
            model_name='property',
            name='price_per_sqm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='السعر لكل متر مربع'),
        ),
        migrations.AlterField(
            model_name='property',
            name='rooms',
            field=models.TextField(blank=True, default='[]', null=True, verbose_name='تفاصيل الغرف'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=6, default=1.0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='سعر الصرف'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='fee_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='مبلغ الرسوم'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='مبلغ الضريبة'),
        ),
    ]
