# Generated by Django 5.1.4 on 2025-04-06 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_remove_property_properties_year_bu_814649_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='بيانات إضافية'),
        ),
        migrations.AlterField(
            model_name='auction',
            name='documents',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='مستندات المزاد'),
        ),
        migrations.AlterField(
            model_name='auction',
            name='images',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='صور المزاد'),
        ),
        migrations.AlterField(
            model_name='auction',
            name='location',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='الموقع الجغرافي'),
        ),
        migrations.AlterField(
            model_name='auction',
            name='videos',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='فيديوهات المزاد'),
        ),
        migrations.AlterField(
            model_name='bid',
            name='device_info',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='معلومات الجهاز'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='files',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='ملفات العقد'),
        ),
        migrations.AlterField(
            model_name='document',
            name='files',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='ملفات المستند'),
        ),
        migrations.AlterField(
            model_name='document',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='بيانات وصفية'),
        ),
        migrations.AlterField(
            model_name='message',
            name='attachments',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='المرفقات'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='files',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='ملفات الدفعة'),
        ),
        migrations.AlterField(
            model_name='property',
            name='documents',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='مستندات العقار'),
        ),
        migrations.AlterField(
            model_name='property',
            name='features',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='المميزات والمرافق'),
        ),
        migrations.AlterField(
            model_name='property',
            name='images',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='صور العقار'),
        ),
        migrations.AlterField(
            model_name='property',
            name='location',
            field=models.JSONField(blank=True, null=True, verbose_name='الموقع الجغرافي'),
        ),
        migrations.AlterField(
            model_name='property',
            name='videos',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='فيديوهات العقار'),
        ),
        migrations.AlterField(
            model_name='propertyview',
            name='historical_views',
            field=models.JSONField(blank=True, default=dict, verbose_name='الإطلالات التاريخية'),
        ),
        migrations.AlterField(
            model_name='propertyview',
            name='images',
            field=models.JSONField(blank=True, default=list, verbose_name='الصور'),
        ),
    ]
