# Generated by Django 5.1.4 on 2025-04-06 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_notification_metadata_alter_auction_documents_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='rooms',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='غرف العقار'),
        ),
    ]
